version: '3.5'

services:
  redis_svc:
    image: redis:6.0.9-alpine
    container_name: redis_container
    restart: always

  app_svc:
    build:
      context: ./
    container_name: app_svc
    restart: always

  celery_worker:
    build:
      context: ./
    container_name: celery_worker
    restart: always
